admcdsi:
    resource: "@ADMCDSIBundle/Resources/config/routing.yml"
    prefix:   /

admc_core:
    resource: "@ADMCCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
