services:
#    admc_core.example:
#        class: ADMC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    admc_core_test:
        class: ADMC\CoreBundle\LdapServices\ADMCTest